### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by ajay-gh** [adarsh-sgh/homenote#4]
it would be nice if 
- the H icon was available / visible in the the richtext editor mode,
- one could turn the homenote feature on and off (without having to select the folder again next time).

**Comment by adarsh-sgh** [comment]
> the H icon was available / visible in the the richtext editor mode,

This is a known Bug in Joplin itself ; [here](https://discourse.joplinapp.org/t/feature-request-toolbar-move-button-locations-viewer-mode-plugin-button-shows-as-gear-icon/20370) it's discussed in detail

>  one could turn the homenote feature on and off (without having to select the folder again next time).

Fortunately it's an inbuilt feature of joplin alllowing us to disable a plugin , you can refer [steps to disable plugin](https://github.com/adarsh-sgh/homenote#disable-restore-default-behaviour)
please correct me If this was not what you were suggesting
