### ISSUE TITLE
Home toolbar icon for jumping, right-click for setting?

### ISSUE THREAD

**Issue by rfkat** [adarsh-sgh/homenote#8]
I like the plugin - and I keep pressing the toolbar icon to go to the "Home" note, thereby accidentally setting a different note as home.

Would it be possible to _set_ via right-click, and to _jump_ via the toolbar icon? That might make the experience a bit more browser-like.

**Comment by rfkat** [comment]
What a pity.

Do you think it would make sense to shift the setting to a menu item, then, and turn the house icon into a "home" button?

**Comment by adarsh-sgh** [comment]
> Do you think it would make sense to shift the setting to a menu item, then, and turn the house icon into a "home" button?

Yupp makes sense;
  it's also possible to control it through settings; if there are users who want the current behavior to continue (toolbar to set homenote) 
  @aynp what do you think of this

**Comment by aynp** [comment]
I think shifting setting to a menu and using toolbar button as 'go to home' would make more sense, as it would be more frequent action than setting new homepage for most people.
